#!/bin/sh
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: pos
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
