version: "3.1"

services:
  db:
    image: postgis/postgis:14-3.1-alpine
    environment:
      POSTGRES_USER: rest
      POSTGRES_PASSWORD: rest123
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8001:8080"
    depends_on:
      - db
